name: phoenix_socket_client
description: A Very Good Project created by Very Good CLI.
version: 0.3.3
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  callback_observable:
    git:
      url: https://github.com/lumpsoid/callback_observable_dart
      ref: "22de0b1d944eb042a1a02f537353ad1ee4d23d2b"
  socket_client:
    git:
      url: https://github.com/lumpsoid/socket_client_dart
      ref: "5116f1962f731fc2523e2e68f652d23c5f90257e"

dev_dependencies:
  mocktail: ^1.0.5
  test: ^1.31.0
  very_good_analysis: ^10.2.0
