defmodule TestServerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :test_server

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # @session_options [
  #  store: :cookie,
  #  key: "_test_server_key",
  #  signing_salt: "SRxENP8w",
  #  same_site: "Lax"
  # ]

  socket "/socket", TestServerWeb.UserSocket,
    websocket: true,
    longpoll: false

  # No static files to serve
  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # plug Plug.Static,
  #  at: "/",
  #  from: :test_server,
  #  gzip: not code_reloading?,
  #  only: TestServerWeb.static_paths(),
  #  raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # No HTTP request bodies being parsed — only WebSocket frames
  # plug Plug.Parsers,
  #   parsers: [:urlencoded, :multipart, :json],
  #   pass: ["*/*"],
  #   json_decoder: Phoenix.json_library()

  # HTTP verb tunneling — irrelevant for sockets
  # plug Plug.MethodOverride

  # HTTP HEAD method handling — irrelevant for sockets
  # plug Plug.Head

  # Sessions are cookie/browser concepts — WebSocket clients don't use HTTP session cookies
  # plug Plug.Session, @session_options

  plug TestServerWeb.Router
end
